"""Raw catalog content, ported from the original seoul-shelf.jsx CONCERNS/PRODUCTS
arrays. This module is the *only* place the product catalog is hardcoded — it
exists to populate the database once (see seed.py); the app itself always reads
from Postgres via app.models.
"""

from .quiz_config import QUIZ_STEPS
from .scoring import STEP_META

# "all" is a special-cased wildcard in scoring.score_product, not a literal quiz
# answer — it's valid on a product's skin_types even though it's never a QUIZ_STEPS
# option value.
VALID_SKIN_TYPES = {
    option["value"]
    for step in QUIZ_STEPS
    if step["id"] == "skin_type"
    for option in step["options"]
} | {"all"}

# Categories scoring.py actually knows how to slot into a routine (ROUTINES/STEP_META).
VALID_CATEGORIES = set(STEP_META.keys())

REQUIRED_PRODUCT_FIELDS = (
    "id",
    "brand",
    "name",
    "category",
    "skin_types",
    "concerns",
    "sensitive_safe",
    "actives",
    "ingredient",
)

CONCERNS = [
    {"id": "acne", "label": "Breakouts & acne"},
    {"id": "dark-spots", "label": "Dark spots & uneven tone"},
    {"id": "redness", "label": "Redness & irritation"},
    {"id": "dullness", "label": "Dullness / no glow"},
    {"id": "aging", "label": "Fine lines & firmness"},
    {"id": "texture", "label": "Rough texture"},
    {"id": "dehydration", "label": "Tightness & dehydration"},
    {"id": "pores", "label": "Visible pores / excess oil"},
]

PRODUCTS = [
    # ---------- CLEANSERS (17) ----------
    {"id": "cosrx-lowph", "brand": "COSRX", "name": "Low pH Good Morning Gel Cleanser", "category": "cleanser", "price": 11, "skin_types": ["oily", "combination"], "concerns": ["acne", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Tea Tree, BHA (Mild)", "blurb": "Gel cleanser that respects your skin barrier while keeping oil in check. A K-beauty rite of passage."},
    {"id": "manyo-oil", "brand": "Ma:nyo", "name": "Pure Cleansing Oil", "category": "cleanser", "price": 18, "skin_types": ["all"], "concerns": ["dullness", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Olive, Argan Oil Blend", "blurb": "The first-step oil cleanse. It melts sunscreen and grime without stripping the skin, and it's Korea's best-selling cleansing oil."},
    {"id": "roundlab-cleanser", "brand": "Round Lab", "name": "1025 Dokdo Cleanser", "category": "cleanser", "price": 16, "skin_types": ["dry", "normal"], "concerns": ["dehydration", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Ulleungdo Deep Sea Water", "blurb": "Creamy, low-irritation wash that leaves zero tight feeling. Beloved by dry and reactive skin."},
    {"id": "bj-plum", "brand": "Beauty of Joseon", "name": "Green Plum Refreshing Cleanser", "category": "cleanser", "price": 14, "skin_types": ["combination", "oily", "normal"], "concerns": ["dullness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Green Plum Water, Mung Bean", "blurb": "pH-balanced foam with a soft, hanbang-inspired formula. Fresh finish without squeak."},
    {"id": "banila-cleanit", "brand": "Banila Co", "name": "Clean It Zero Cleansing Balm Original", "category": "cleanser", "price": 22, "skin_types": ["all"], "concerns": ["dullness", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Sherbet Balm, Vitamin E", "blurb": "The original sherbet-to-oil balm that started the cleansing balm craze. Melts a full face of makeup in one pass."},
    {"id": "heimish-allclean", "brand": "Heimish", "name": "All Clean Balm", "category": "cleanser", "price": 19, "skin_types": ["all"], "concerns": ["dullness", "pores"], "sensitive_safe": False, "actives": False, "ingredient": "Shea Butter, Citrus Herb Oils", "blurb": "A cult first cleanser with a spa-like herbal scent. Skip it if fragrance bothers you; love it if it doesn't."},
    {"id": "skin1004-cleansingoil", "brand": "Skin1004", "name": "Madagascar Centella Light Cleansing Oil", "category": "cleanser", "price": 19, "skin_types": ["all"], "concerns": ["redness", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Madagascar Centella", "blurb": "A featherweight cleansing oil that rinses clean without stinging eyes or upsetting reactive skin."},
    {"id": "anua-cleansingoil", "brand": "Anua", "name": "Heartleaf Pore Control Cleansing Oil", "category": "cleanser", "price": 26, "skin_types": ["oily", "combination", "all"], "concerns": ["pores", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Heartleaf, Ester Oils", "blurb": "The viral blackhead-melting first cleanse. Massage it in and watch grits actually come out."},
    {"id": "beplain-mungbean", "brand": "Beplain", "name": "Mung Bean pH-Balanced Cleansing Foam", "category": "cleanser", "price": 15, "skin_types": ["all"], "concerns": ["redness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "33% Mung Bean Extract", "blurb": "An Olive Young award perennial for sensitive skin. Cleans thoroughly with zero post-wash tightness."},
    {"id": "skin1004-foam", "brand": "Skin1004", "name": "Madagascar Centella Ampoule Foam", "category": "cleanser", "price": 14, "skin_types": ["oily", "combination", "normal"], "concerns": ["redness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Centella, Mild Surfactants", "blurb": "A dense whipped foam that treats cleansing like a calming step instead of a stripping one."},
    {"id": "sbm-acneclear", "brand": "Some By Mi", "name": "AHA BHA PHA 30 Days Miracle Acne Clear Foam", "category": "cleanser", "price": 14, "skin_types": ["oily", "combination"], "concerns": ["acne", "texture"], "sensitive_safe": False, "actives": True, "ingredient": "Triple Acid, Tea Tree", "blurb": "The wash-off half of the Miracle line. A low-dose acid cleanse for congestion-prone weeks."},
    {"id": "bj-cleansingbalm", "brand": "Beauty of Joseon", "name": "Radiance Cleansing Balm", "category": "cleanser", "price": 18, "skin_types": ["all"], "concerns": ["dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Rice Bran, Grain Ferments", "blurb": "Hanbang double-cleansing: a soft balm that leaves skin looking polished, not stripped."},
    {"id": "etude-whipcleanser", "brand": "Etude", "name": "SoonJung pH 6.5 Whip Cleanser", "category": "cleanser", "price": 13, "skin_types": ["dry", "normal", "all"], "concerns": ["redness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Panthenol, Madecassoside", "blurb": "The gentlest foam in the SoonJung family. Airy whip texture, nothing your barrier will complain about."},
    {"id": "klairs-blackoil", "brand": "Klairs", "name": "Gentle Black Deep Cleansing Oil", "category": "cleanser", "price": 23, "skin_types": ["all"], "concerns": ["pores", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Black Sesame, Black Bean Oil", "blurb": "A nutrient-dense first cleanse built on black seed oils. Thorough, quiet, dependable."},
    {"id": "sulwhasoo-ginsengcleanser", "brand": "Sulwhasoo", "name": "Concentrated Ginseng Rejuvenating Cleansing Foam", "category": "cleanser", "price": 48, "skin_types": ["dry", "normal", "all"], "concerns": ["aging", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Ginseng Amino Complex, Ginseng Peptide", "blurb": "Sulwhasoo's luxury ginseng-first cleanse. A cushiony, rejuvenating foam for the anti-aging routine that starts at step one."},
    {"id": "goodal-vitc-cleanser", "brand": "Goodal", "name": "Green Tangerine Vita C Cleansing Foam", "category": "cleanser", "price": 16, "skin_types": ["all"], "concerns": ["dark-spots", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Green Tangerine Vitamin C, Niacinamide", "blurb": "A brightening foam built on peak-season green tangerines. Gentle enough for sensitive skin, formulated to fade tone unevenness from the first step."},
    {"id": "imfrom-figenzyme", "brand": "I'm From", "name": "Fig Enzyme Powder Cleanser", "category": "cleanser", "price": 24, "skin_types": ["dry", "normal", "all"], "concerns": ["texture", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Fig & Papaya Enzymes, Nuruk Ferment", "blurb": "A powder-to-foam wash that lifts dead skin and buildup with fig, papaya, and nuruk enzymes instead of a leave-on acid. Gentle enough for the driest, most reactive skin to use as a weekly resurfacer."},
    # ---------- TONERS (19) ----------
    {"id": "anua-heartleaf", "brand": "Anua", "name": "Heartleaf 77% Soothing Toner", "category": "toner", "price": 19, "skin_types": ["all"], "concerns": ["redness", "acne", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "77% Heartleaf Extract", "blurb": "The calming toner that took over Korean pharmacies. Drenches angry skin in heartleaf."},
    {"id": "roundlab-birch", "brand": "Round Lab", "name": "Birch Juice Moisturizing Toner", "category": "toner", "price": 17, "skin_types": ["dry", "normal", "combination"], "concerns": ["dehydration", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Birch Sap, Hyaluronic Acid", "blurb": "Watery hydration layers beautifully under everything. A Korean daily-routine staple."},
    {"id": "cosrx-ahabha", "brand": "COSRX", "name": "AHA/BHA Clarifying Treatment Toner", "category": "toner", "price": 13, "skin_types": ["oily", "combination"], "concerns": ["texture", "acne", "pores"], "sensitive_safe": False, "actives": True, "ingredient": "AHA, BHA (Gentle %)", "blurb": "Light daily exfoliating toner that keeps texture and congestion moving out."},
    {"id": "isntree-ha", "brand": "Isntree", "name": "Hyaluronic Acid Toner Plus", "category": "toner", "price": 17, "skin_types": ["dry", "all"], "concerns": ["dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "8 Types of Hyaluronic Acid", "blurb": "A tall glass of water for the face. Slightly viscous, deeply quenching."},
    {"id": "numbuzin-3", "brand": "Numbuzin", "name": "No.3 Skin Softening Serum Toner", "category": "toner", "price": 22, "skin_types": ["normal", "combination", "dry"], "concerns": ["dullness", "texture"], "sensitive_safe": True, "actives": False, "ingredient": "Fermented Complex (Galactomyces)", "blurb": "The 'glass skin filter' toner. Fermented essences smooth and brighten skin over a few weeks of regular use."},
    {"id": "imfrom-ricetoner", "brand": "I'm From", "name": "Rice Toner", "category": "toner", "price": 26, "skin_types": ["dry", "normal", "all"], "concerns": ["dullness", "dark-spots", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "77.78% Rice Extract", "blurb": "Milky rice water that brightens the way traditional Korean routines always promised. A TikTok darling that earns it."},
    {"id": "klairs-supple", "brand": "Klairs", "name": "Supple Preparation Unscented Toner", "category": "toner", "price": 22, "skin_types": ["all"], "concerns": ["dehydration", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Hyaluronic Acid, Beta-Glucan", "blurb": "The fragrance-free classic that made 'seven skin method' famous. Layers endlessly without stickiness."},
    {"id": "skin1004-toner", "brand": "Skin1004", "name": "Madagascar Centella Toning Toner", "category": "toner", "price": 17, "skin_types": ["all"], "concerns": ["redness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Centella, PHA (Trace)", "blurb": "Calming hydration with the faintest hint of resurfacing. A do-no-harm daily prep step."},
    {"id": "sbm-miracletoner", "brand": "Some By Mi", "name": "AHA BHA PHA 30 Days Miracle Toner", "category": "toner", "price": 15, "skin_types": ["oily", "combination"], "concerns": ["acne", "texture", "pores"], "sensitive_safe": False, "actives": True, "ingredient": "Triple Acid, Tea Tree", "blurb": "The gateway exfoliating toner for breakout-prone skin. Gentle percentages, cumulative results."},
    {"id": "mediheal-pads", "brand": "Mediheal", "name": "Madecassoside Blemish Pads", "category": "toner", "price": 22, "skin_types": ["all"], "concerns": ["redness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Madecassoside, Cica", "blurb": "Toner pads soaked in calm. Press a couple onto angry spots like mini targeted masks."},
    {"id": "cosrx-clearpad", "brand": "COSRX", "name": "One Step Original Clear Pads", "category": "toner", "price": 22, "skin_types": ["oily", "combination"], "concerns": ["acne", "pores", "texture"], "sensitive_safe": False, "actives": True, "ingredient": "BHA, Willow Bark Water", "blurb": "One swipe of BHA housekeeping a day. The lazy-efficient way to keep pores in line."},
    {"id": "haruharu-blackrice", "brand": "Haruharu Wonder", "name": "Black Rice Hyaluronic Toner (Unscented)", "category": "toner", "price": 18, "skin_types": ["all"], "concerns": ["dehydration", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Fermented Black Rice", "blurb": "Fermented black rice in a slightly viscous, deeply comforting layer. Quiet luxury for the toner step."},
    {"id": "pyunkang-essencetoner", "brand": "Pyunkang Yul", "name": "Essence Toner", "category": "toner", "price": 18, "skin_types": ["dry", "all"], "concerns": ["dehydration", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "91% Milk Vetch Root Extract", "blurb": "Seven ingredients, one job: hydrate without irritating. Minimalism from an oriental medicine clinic."},
    {"id": "roundlab-dokdotoner", "brand": "Round Lab", "name": "1025 Dokdo Toner", "category": "toner", "price": 18, "skin_types": ["all"], "concerns": ["dehydration", "texture"], "sensitive_safe": True, "actives": False, "ingredient": "Ulleungdo Deep Sea Water", "blurb": "Korea's best-selling toner, full stop. Mineral-rich water that gently smooths as it hydrates."},
    {"id": "abib-heartleaf", "brand": "Abib", "name": "Heartleaf Calming Toner Skin Booster", "category": "toner", "price": 20, "skin_types": ["all"], "concerns": ["redness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Heartleaf Extract", "blurb": "Abib's take on the heartleaf calm-down. Slightly richer than Anua's, great for stressed barriers."},
    {"id": "cosrx-bhaliquid", "brand": "COSRX", "name": "BHA Blackhead Power Liquid", "category": "toner", "price": 17, "skin_types": ["oily", "combination"], "concerns": ["texture", "pores"], "sensitive_safe": False, "actives": True, "ingredient": "4% Betaine Salicylate (BHA)", "blurb": "The liquid that put COSRX's BHA on the map. Daily exfoliation for congested pores and rough patches."},
    {"id": "neogen-biopeel", "brand": "Neogen", "name": "Bio-Peel Gauze Peeling Pad (Lemon)", "category": "toner", "price": 25, "skin_types": ["oily", "combination", "normal"], "concerns": ["texture", "dullness", "pores"], "sensitive_safe": False, "actives": True, "ingredient": "AHA/BHA Gauze Exfoliating Pad", "blurb": "The double-sided pad that made at-home peels routine. Rough side buffs, smooth side finishes, texture gone by morning."},
    {"id": "whamisa-deeprich", "brand": "Whamisa", "name": "Organic Flowers Toner Deep Rich", "category": "toner", "price": 34, "skin_types": ["dry", "normal", "all"], "concerns": ["aging", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Fermented Organic Flower Extract Complex", "blurb": "A serum-thick, twice-fermented toner from Korea's organic skincare pioneer. Antioxidant-rich and deeply plumping for skin that wants more than water."},
    {"id": "cosrx-porelessliquid", "brand": "COSRX", "name": "Two in One Poreless Power Liquid", "category": "toner", "price": 21, "skin_types": ["dry", "normal", "combination", "all"], "concerns": ["pores", "texture"], "sensitive_safe": True, "actives": True, "ingredient": "0.1% BHA, Niacinamide, Hyaluronic Acid", "blurb": "A whisper-low 0.1% BHA dose paired with niacinamide and hyaluronic acid — pore care gentle enough for dry and sensitive skin that can't tolerate a stronger acid toner."},
    # ---------- ESSENCES (15) ----------
    {"id": "cosrx-snail", "brand": "COSRX", "name": "Advanced Snail 96 Mucin Power Essence", "category": "essence", "price": 17, "skin_types": ["all"], "concerns": ["dehydration", "redness", "aging"], "sensitive_safe": True, "actives": False, "ingredient": "96% Snail Secretion Filtrate", "blurb": "The global K-beauty icon. Repairs, plumps, and gives that dewy bounce."},
    {"id": "missha-fte", "brand": "Missha", "name": "Time Revolution First Treatment Essence", "category": "essence", "price": 35, "skin_types": ["all"], "concerns": ["aging", "dullness", "texture"], "sensitive_safe": True, "actives": False, "ingredient": "Fermented Yeast Concentrate", "blurb": "Korea's answer to luxury treatment essences at a third of the price."},
    {"id": "mixsoon-bean", "brand": "Mixsoon", "name": "Bean Essence", "category": "essence", "price": 20, "skin_types": ["normal", "combination", "oily"], "concerns": ["texture", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Fermented Soybean", "blurb": "Viral for a reason: it gently lifts dead skin cells while it hydrates."},
    {"id": "cosrx-galactomyces", "brand": "COSRX", "name": "Galactomyces 95 Tone Balancing Essence", "category": "essence", "price": 18, "skin_types": ["all"], "concerns": ["dark-spots", "dullness", "aging"], "sensitive_safe": True, "actives": False, "ingredient": "95% Galactomyces Ferment, Niacinamide", "blurb": "Fermented brightening at drugstore prices. Evens tone and softens fine lines with daily patience."},
    {"id": "bj-ginseng", "brand": "Beauty of Joseon", "name": "Ginseng Essence Water", "category": "essence", "price": 18, "skin_types": ["dry", "normal", "all"], "concerns": ["aging", "dullness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "80% Ginseng Root Water", "blurb": "A toner-essence hybrid steeped in ginseng. Hanbang firmness and glow in the lightest possible layer."},
    {"id": "benton-snailbee", "brand": "Benton", "name": "Snail Bee High Content Essence", "category": "essence", "price": 18, "skin_types": ["all"], "concerns": ["acne", "dark-spots", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Snail Secretion, Bee Venom, Niacinamide", "blurb": "The indie cult favorite that fades post-acne marks while calming what's still angry."},
    {"id": "skin1004-ampoule", "brand": "Skin1004", "name": "Madagascar Centella Ampoule", "category": "essence", "price": 18, "skin_types": ["all"], "concerns": ["redness", "acne", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "100% Centella Asiatica Extract", "blurb": "One ingredient, endlessly repurchased. The watery ampoule reactive skin treats like a security blanket."},
    {"id": "dalba-spray", "brand": "d'Alba", "name": "White Truffle First Spray Serum", "category": "essence", "price": 30, "skin_types": ["all"], "concerns": ["dullness", "dehydration", "aging"], "sensitive_safe": True, "actives": False, "ingredient": "Italian White Truffle", "blurb": "Part essence, part mist, all glow. Spritz it before serums or over makeup for a midday revival."},
    {"id": "secretkey-fte", "brand": "Secret Key", "name": "Starting Treatment Essence", "category": "essence", "price": 15, "skin_types": ["all"], "concerns": ["aging", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Galactomyces Ferment Filtrate", "blurb": "The budget first-treatment essence. Seven benefits in one bottle, dupes the luxury players convincingly."},
    {"id": "cosrx-propolis", "brand": "COSRX", "name": "Full Fit Propolis Light Ampule", "category": "essence", "price": 23, "skin_types": ["dry", "normal"], "concerns": ["dullness", "aging"], "sensitive_safe": True, "actives": False, "ingredient": "83% Propolis Extract", "blurb": "Honey-glow in a dropper. Antioxidant nourishment that leaves a lit-from-within finish."},
    {"id": "missha-artemisia", "brand": "Missha", "name": "Time Revolution Artemisia Calming Essence", "category": "essence", "price": 30, "skin_types": ["all"], "concerns": ["redness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Double-Fermented Artemisia", "blurb": "Mugwort, fermented twice, and nothing else it doesn't need. The flare-up first responder."},
    {"id": "neogen-ferment", "brand": "Neogen", "name": "Real Ferment Micro Essence", "category": "essence", "price": 38, "skin_types": ["all"], "concerns": ["dullness", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "93% Fermented Complex", "blurb": "A fermentation-forward essence built for sensitive skin with visible pores. Splurgier, but dense with actives-adjacent goodness."},
    {"id": "mizon-snailrepair", "brand": "Mizon", "name": "Snail Repair Intensive Ampoule", "category": "essence", "price": 24, "skin_types": ["dry", "normal", "all"], "concerns": ["dark-spots", "aging", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "92% Snail Secretion Filtrate", "blurb": "One of the original snail ampoules -- thick, repair-focused, and built to fade old marks over months of use."},
    {"id": "missha-nightrepair", "brand": "Missha", "name": "Time Revolution Night Repair Ampoule", "category": "essence", "price": 32, "skin_types": ["all"], "concerns": ["dullness", "aging", "dark-spots"], "sensitive_safe": True, "actives": False, "ingredient": "90% Bifida Ferment Lysate", "blurb": "Korea's best-selling fermented ampoule, worn overnight to fade dullness and old spots by sunrise."},
    {"id": "mixsoon-galactomyces", "brand": "Mixsoon", "name": "Galactomyces Pure Essence 80", "category": "essence", "price": 24, "skin_types": ["dry", "normal", "combination"], "concerns": ["dark-spots", "texture", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "80% Galactomyces Ferment Filtrate", "blurb": "Mixsoon's fermented follow-up to the Bean Essence. Smooths texture and evens tone one thin layer at a time."},
    # ---------- SERUMS (23) ----------
    {"id": "bj-glow", "brand": "Beauty of Joseon", "name": "Glow Deep Serum", "category": "serum", "price": 17, "skin_types": ["all"], "concerns": ["dark-spots", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Alpha Arbutin, Rice Bran", "blurb": "Hanbang brightening without irritation. Fades spots and evens tone gradually."},
    {"id": "anua-niacinamide", "brand": "Anua", "name": "Niacinamide 10% + TXA 4% Serum", "category": "serum", "price": 24, "skin_types": ["oily", "combination", "normal"], "concerns": ["dark-spots", "pores"], "sensitive_safe": False, "actives": True, "ingredient": "Niacinamide, Tranexamic Acid", "blurb": "A heavier hitter for stubborn post-acne marks and enlarged pores."},
    {"id": "torriden-dive", "brand": "Torriden", "name": "Dive-In Low Molecular Hyaluronic Serum", "category": "serum", "price": 18, "skin_types": ["all"], "concerns": ["dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "5 Sizes of Hyaluronic Acid", "blurb": "Feather-light water serum that sinks in instantly. The dehydration fixer."},
    {"id": "sbm-miracle", "brand": "Some By Mi", "name": "AHA BHA PHA 30 Days Miracle Serum", "category": "serum", "price": 20, "skin_types": ["oily", "combination"], "concerns": ["acne", "texture"], "sensitive_safe": False, "actives": True, "ingredient": "Triple Acid, Tea Tree", "blurb": "The acne-routine classic. Keeps pores clear and calms active breakouts."},
    {"id": "bj-revive", "brand": "Beauty of Joseon", "name": "Revive Serum: Ginseng + Snail", "category": "serum", "price": 17, "skin_types": ["dry", "normal", "all"], "concerns": ["aging", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "63% Ginseng Root Water", "blurb": "Traditional ginseng meets snail mucin for firmness and glow."},
    {"id": "purito-centella", "brand": "Purito", "name": "Wonder Releaf Centella Serum (Unscented)", "category": "serum", "price": 18, "skin_types": ["all"], "concerns": ["redness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Centella Asiatica 49%", "blurb": "Fragrance-free cica serum built for reactive, stressed-out skin."},
    {"id": "cosrx-peptide", "brand": "COSRX", "name": "The 6 Peptide Skin Booster Serum", "category": "serum", "price": 25, "skin_types": ["all"], "concerns": ["aging", "dullness", "texture"], "sensitive_safe": True, "actives": False, "ingredient": "6-Peptide Complex, Niacinamide", "blurb": "Peptide firming without the retinol commitment. Gentle enough to layer into any routine."},
    {"id": "cosrx-retinol", "brand": "COSRX", "name": "The Retinol 0.1 Cream", "category": "serum", "price": 22, "skin_types": ["normal", "combination", "oily"], "concerns": ["aging", "texture", "dark-spots"], "sensitive_safe": False, "actives": True, "ingredient": "Retinol 0.1%, Adenosine, Panthenol", "blurb": "A beginner-strength retinol buffered with soothers. Start two nights a week and build up."},
    {"id": "medicube-vitac", "brand": "Medicube", "name": "Deep Vita C Ampoule", "category": "serum", "price": 28, "skin_types": ["normal", "combination", "oily"], "concerns": ["dark-spots", "dullness"], "sensitive_safe": False, "actives": True, "ingredient": "Pure Vitamin C, Niacinamide", "blurb": "A morning brightening hitter for stubborn spots. Pair it with SPF religiously."},
    {"id": "goodal-vitac", "brand": "Goodal", "name": "Green Tangerine Vita C Dark Spot Serum", "category": "serum", "price": 22, "skin_types": ["normal", "combination", "oily"], "concerns": ["dark-spots", "dullness"], "sensitive_safe": False, "actives": True, "ingredient": "Green Tangerine Vitamin C", "blurb": "The dark-spot serum Korean pharmacies can't keep stocked. Citrus-derived vitamin C with a gentle acid assist."},
    {"id": "anua-pdrn", "brand": "Anua", "name": "PDRN Hyaluronic Acid Capsule 100 Serum", "category": "serum", "price": 26, "skin_types": ["all"], "concerns": ["dehydration", "aging", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "PDRN, Hyaluronic Acid, Collagen", "blurb": "2026's buzziest ingredient in a watery, bouncy serum. The at-home version of the salmon-DNA facial."},
    {"id": "klairs-vitamindrop", "brand": "Klairs", "name": "Freshly Juiced Vitamin Drop", "category": "serum", "price": 23, "skin_types": ["all"], "concerns": ["dark-spots", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "5% Vitamin C (Gentle)", "blurb": "The training-wheels vitamin C. Low enough to skip the sting, consistent enough to fade marks."},
    {"id": "iunik-teatree", "brand": "iUNIK", "name": "Tea Tree Relief Serum", "category": "serum", "price": 17, "skin_types": ["oily", "combination"], "concerns": ["acne", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "67% Tea Tree Leaf Water", "blurb": "Breakout first-aid in serum form. Calms without drying, which is rarer than it should be."},
    {"id": "axisy-darkspot", "brand": "AXIS-Y", "name": "Dark Spot Correcting Glow Serum", "category": "serum", "price": 20, "skin_types": ["all"], "concerns": ["dark-spots", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "5% Niacinamide, Squalane", "blurb": "The gentle-but-serious spot fader. A community favorite for post-acne marks on sensitive skin."},
    {"id": "numbuzin-5", "brand": "Numbuzin", "name": "No.5 Vitamin-Niacinamide Concentrated Serum", "category": "serum", "price": 26, "skin_types": ["normal", "combination", "oily"], "concerns": ["dark-spots", "dullness"], "sensitive_safe": False, "actives": True, "ingredient": "Vitamin C + 12 Vitamins, Niacinamide", "blurb": "The 'filter number 5' glow serum. A vitamin cocktail for tone that photographs dull."},
    {"id": "torriden-cellmazing", "brand": "Torriden", "name": "Cellmazing Firming Collagen Ampoule", "category": "serum", "price": 25, "skin_types": ["dry", "normal", "all"], "concerns": ["aging", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Low-Molecular Collagen", "blurb": "The Dive-In brand grows up: collagen and firming peptides in the same weightless texture."},
    {"id": "medicube-pdrn", "brand": "Medicube", "name": "PDRN Pink Peptide Serum", "category": "serum", "price": 29, "skin_types": ["all"], "concerns": ["aging", "dullness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "PDRN, Peptide Complex", "blurb": "The pink serum all over Korean social media. Bounce and firmness with a glass-skin finish."},
    {"id": "bj-calming", "brand": "Beauty of Joseon", "name": "Calming Serum: Green Tea + Panthenol", "category": "serum", "price": 17, "skin_types": ["oily", "combination", "all"], "concerns": ["redness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Green Tea, Panthenol", "blurb": "The quiet sibling of the Glow serum. Settles oil and irritation with hanbang restraint."},
    {"id": "cosrx-vitc23", "brand": "COSRX", "name": "The Vitamin C 23 Serum", "category": "serum", "price": 25, "skin_types": ["normal", "combination", "oily"], "concerns": ["dark-spots", "dullness", "texture"], "sensitive_safe": False, "actives": True, "ingredient": "23% Pure Vitamin C", "blurb": "The strong stuff. A high-percentage vitamin C for skin that's graduated past the gentle options."},
    {"id": "skin1004-blueserum", "brand": "Skin1004", "name": "Hyalu-Cica Blue Serum", "category": "serum", "price": 17, "skin_types": ["all"], "concerns": ["dehydration", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Hyaluronic Acid, Centella", "blurb": "Hydration and calm in one blue bottle. The safe pick when your skin can't decide what it's mad about."},
    {"id": "manyo-bifida", "brand": "Ma:nyo", "name": "Bifida Biome Ampoule", "category": "serum", "price": 32, "skin_types": ["combination", "oily", "normal"], "concerns": ["dark-spots", "texture", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Bifida Ferment Lysate", "blurb": "A fermentation-heavy ampoule that refines pore texture and evens tone without a hint of sting."},
    {"id": "iunik-propolisvitc", "brand": "iUNIK", "name": "Propolis Vitamin Synergy Serum", "category": "serum", "price": 19, "skin_types": ["all"], "concerns": ["dark-spots", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Propolis, Vitamin C", "blurb": "Propolis softens what vitamin C brightens. A cult favorite for fading spots without the usual sting."},
    {"id": "purito-buffet", "brand": "Purito", "name": "Centella Green Level Buffet Serum", "category": "serum", "price": 20, "skin_types": ["combination", "oily", "normal"], "concerns": ["texture", "dullness", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Niacinamide, Adenosine, Centella", "blurb": "A multi-active buffet that smooths texture and refines pores without a single harsh percentage."},
    {"id": "bj-glowserum-propolis", "brand": "Beauty of Joseon", "name": "Glow Serum: Propolis + Niacinamide", "category": "serum", "price": 19, "skin_types": ["dry", "normal", "all"], "concerns": ["pores", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "59.94% Propolis Extract, 2% Niacinamide", "blurb": "Propolis calms while niacinamide refines the look of enlarged pores and evens tone — hanbang-adjacent glow without an acid in sight."},
    # ---------- MOISTURIZERS (21) ----------
    {"id": "bj-dynasty", "brand": "Beauty of Joseon", "name": "Dynasty Cream", "category": "moisturizer", "price": 24, "skin_types": ["dry", "normal"], "concerns": ["aging", "dehydration", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Rice Bran Water, Ginseng", "blurb": "Rich but never greasy. This hanbang cream leaves a nourished, royal-court finish."},
    {"id": "cosrx-oilfree", "brand": "COSRX", "name": "Oil-Free Ultra-Moisturizing Lotion", "category": "moisturizer", "price": 20, "skin_types": ["oily", "combination"], "concerns": ["acne", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Birch Sap 70%", "blurb": "Hydration with zero heaviness. Made for skin that hates feeling coated."},
    {"id": "illiyoon-ceramide", "brand": "Illiyoon", "name": "Ceramide Ato Concentrate Cream", "category": "moisturizer", "price": 16, "skin_types": ["dry", "all"], "concerns": ["redness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Ceramide Capsule Complex", "blurb": "A Korean pharmacy hero for barrier repair. Gentle enough for eczema-prone skin."},
    {"id": "etude-soonjung", "brand": "Etude", "name": "SoonJung 2x Barrier Intensive Cream", "category": "moisturizer", "price": 18, "skin_types": ["all"], "concerns": ["redness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Panthenol, Madecassoside", "blurb": "Minimalist formula, maximum calm. The sensitive-skin default in Korea."},
    {"id": "torriden-cream", "brand": "Torriden", "name": "Dive-In Soothing Cream", "category": "moisturizer", "price": 22, "skin_types": ["combination", "normal", "oily"], "concerns": ["dehydration", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Low-Molecular HA, Allantoin", "blurb": "Gel-cream texture that cools on contact and locks the watery layers in."},
    {"id": "aestura-atobarrier", "brand": "Aestura", "name": "Atobarrier 365 Cream", "category": "moisturizer", "price": 28, "skin_types": ["dry", "all"], "concerns": ["redness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "High-Density Ceramide Capsules", "blurb": "Korea's derm-office barrier cream gone mainstream. Cashmere texture, serious ceramide credentials."},
    {"id": "anua-barrier", "brand": "Anua", "name": "3 Ceramide Panthenol Moisture Barrier Cream", "category": "moisturizer", "price": 24, "skin_types": ["dry", "normal", "all"], "concerns": ["dehydration", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Triple Ceramides, Panthenol", "blurb": "Anua's barrier-repair follow-up to the heartleaf empire. Cushiony, unfussy, repurchase-able."},
    {"id": "cosrx-propoliscream", "brand": "COSRX", "name": "Full Fit Propolis Light Cream", "category": "moisturizer", "price": 26, "skin_types": ["dry", "normal"], "concerns": ["dullness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "65% Propolis Extract", "blurb": "Honey-dipped hydration with a glow finish. Rich in feel, light in weight."},
    {"id": "skin1004-cream", "brand": "Skin1004", "name": "Madagascar Centella Soothing Cream", "category": "moisturizer", "price": 19, "skin_types": ["combination", "oily", "all"], "concerns": ["redness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Centella, Panthenol", "blurb": "A gel-cream that finishes the centella routine the way it started: calmly."},
    {"id": "drjart-cicapair", "brand": "Dr.Jart+", "name": "Cicapair Tiger Grass Cream", "category": "moisturizer", "price": 48, "skin_types": ["all"], "concerns": ["redness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Tiger Grass (Centella) Complex", "blurb": "The department-store redness fixer. Pricier, but the flush-prone swear nothing else compares."},
    {"id": "belif-aquabomb", "brand": "Belif", "name": "The True Cream Aqua Bomb", "category": "moisturizer", "price": 38, "skin_types": ["combination", "normal", "oily"], "concerns": ["dehydration", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Lady's Mantle, Herb Extracts", "blurb": "The bouncy gel-cream that made 'aqua bomb' a category. Instant plump, zero grease."},
    {"id": "laneige-waterbank", "brand": "Laneige", "name": "Water Bank Blue Hyaluronic Cream", "category": "moisturizer", "price": 40, "skin_types": ["dry", "normal"], "concerns": ["dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Blue Hyaluronic Acid", "blurb": "Laneige's flagship daytime moisture. Deep hydration engineered from fermented blue-green algae HA."},
    {"id": "medicube-jelly", "brand": "Medicube", "name": "Collagen Niacinamide Jelly Cream", "category": "moisturizer", "price": 27, "skin_types": ["all"], "concerns": ["aging", "dullness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Freeze-Dried Collagen, Niacinamide", "blurb": "The jiggly pink jelly all over your feed. Bounce-back hydration with a brightening undertone."},
    {"id": "snature-squalane", "brand": "S.Nature", "name": "Aqua Squalane Moisturizing Cream", "category": "moisturizer", "price": 28, "skin_types": ["dry", "normal"], "concerns": ["dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Plant Squalane", "blurb": "A quiet Olive Young bestseller: squalane-rich moisture that mimics skin's own oils."},
    {"id": "bioheal-lifting", "brand": "Bioheal BOH", "name": "Probioderm 3D Lifting Cream", "category": "moisturizer", "price": 38, "skin_types": ["dry", "normal", "all"], "concerns": ["aging", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Probiotic Ferment, Collagen", "blurb": "Korea's breakout 'lifting cream' of the moment. Firms with probiotics instead of harsh actives."},
    {"id": "skin1004-retinolcica", "brand": "Skin1004", "name": "Madagascar Centella Retinol Cica Cream", "category": "moisturizer", "price": 26, "skin_types": ["normal", "combination", "all"], "concerns": ["aging", "texture", "dark-spots"], "sensitive_safe": False, "actives": True, "ingredient": "Encapsulated Retinol, Centella", "blurb": "Centella buffers a real dose of retinol, smoothing texture and fading spots without the usual redness tax."},
    {"id": "klairs-richmoist", "brand": "Klairs", "name": "Rich Moist Soothing Cream", "category": "moisturizer", "price": 24, "skin_types": ["dry", "normal", "all"], "concerns": ["dehydration", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Beta-Glucan, Ceramide", "blurb": "The heavier sibling to Klairs' toner line. Ceramide-rich comfort for skin that needs more than a serum can give."},
    {"id": "roundlab-dokdocream", "brand": "Round Lab", "name": "1025 Dokdo Cream", "category": "moisturizer", "price": 19, "skin_types": ["dry", "normal"], "concerns": ["dehydration", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Ulleungdo Deep Sea Water", "blurb": "The cream that finishes the Dokdo lineup. Mineral-rich and unbothered by fragrance or fuss."},
    {"id": "haruharu-blackricecream", "brand": "Haruharu Wonder", "name": "Black Rice New Moisture Barrier Cream", "category": "moisturizer", "price": 24, "skin_types": ["dry", "normal", "all"], "concerns": ["dehydration", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Fermented Black Rice, Ceramide", "blurb": "The cream companion to Haruharu's cult toner. Fermented black rice richness for skin that's tired of feeling tight."},
    {"id": "innisfree-bijalotion", "brand": "innisfree", "name": "Bija Trouble Facial Lotion", "category": "moisturizer", "price": 15, "skin_types": ["oily", "combination", "normal"], "concerns": ["acne", "pores", "redness"], "sensitive_safe": False, "actives": True, "ingredient": "Jeju Bija Oil, Salicylic Acid", "blurb": "A gel-lotion that balances oil and calms breakouts without clogging. Jeju torreya seed oil plus a mild BHA assist for trouble-prone skin."},
    {"id": "dralthea-345relief", "brand": "Dr. Althea", "name": "345 Relief Cream", "category": "moisturizer", "price": 25, "skin_types": ["dry", "normal", "all"], "concerns": ["pores", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Ceramide NP, Niacinamide, Centella Asiatica Water", "blurb": "A vegan gel-cream built on ceramide and niacinamide to soothe while refining pore appearance — rich enough for dry skin, light enough not to clog."},
    # ---------- SPF (22) ----------
    {"id": "bj-reliefsun", "brand": "Beauty of Joseon", "name": "Relief Sun: Rice + Probiotics SPF50+", "category": "spf", "price": 16, "skin_types": ["all"], "concerns": ["dark-spots", "aging", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Rice Extract, Grain Probiotics", "blurb": "The sunscreen that broke the internet. Feels like a light moisturizer, with zero white cast."},
    {"id": "roundlab-sun", "brand": "Round Lab", "name": "Birch Juice Moisturizing Sun Cream SPF50+", "category": "spf", "price": 20, "skin_types": ["dry", "normal"], "concerns": ["dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Birch Sap, Hyaluronic Acid", "blurb": "Hydrating daily SPF that doubles as a glowy base layer."},
    {"id": "skin1004-sun", "brand": "Skin1004", "name": "Hyalu-Cica Water-Fit Sun Serum SPF50+", "category": "spf", "price": 20, "skin_types": ["oily", "combination"], "concerns": ["redness", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Madagascar Centella", "blurb": "Serum-texture sunscreen that disappears on oily skin. No shine, no pilling."},
    {"id": "isntree-sungel", "brand": "Isntree", "name": "Hyaluronic Acid Watery Sun Gel SPF50+", "category": "spf", "price": 15, "skin_types": ["oily", "combination", "normal"], "concerns": ["dehydration", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "8 Types of Hyaluronic Acid", "blurb": "True gel texture that sinks in within seconds and stays matte. The oily-skin sunscreen answer, with zero white cast."},
    {"id": "torriden-sun", "brand": "Torriden", "name": "Dive-In Watery Moisture Sun Cream SPF50+", "category": "spf", "price": 18, "skin_types": ["dry", "normal"], "concerns": ["dehydration", "aging"], "sensitive_safe": True, "actives": False, "ingredient": "5D Hyaluronic Acid Complex", "blurb": "SPF that applies like a serum and hydrates for hours. The Dive-In line's daily finisher."},
    {"id": "cosrx-aloesun", "brand": "COSRX", "name": "Aloe Soothing Sun Cream SPF50", "category": "spf", "price": 14, "skin_types": ["all"], "concerns": ["redness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Aloe Arborescens Leaf Extract", "blurb": "Budget-friendly, non-comedogenic sun protection that calms while it shields. A no-drama daily default."},
    {"id": "bj-ginsengsun", "brand": "Beauty of Joseon", "name": "Ginseng Moist Sun Serum SPF50+", "category": "spf", "price": 18, "skin_types": ["dry", "normal"], "concerns": ["aging", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Ginseng, Grain Ferments", "blurb": "Relief Sun's richer sibling. Anti-aging hanbang care that happens to be an excellent sunscreen."},
    {"id": "roundlab-sunserum", "brand": "Round Lab", "name": "Birch Juice Moisturizing Sun Serum SPF50+", "category": "spf", "price": 22, "skin_types": ["all"], "concerns": ["dehydration", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Birch Sap, Hyaluronic Acid", "blurb": "A current Olive Young #1. Even lighter than the sun cream — SPF you forget you're wearing."},
    {"id": "missha-aquasun", "brand": "Missha", "name": "All Around Safe Block Aqua Sun Gel SPF50+", "category": "spf", "price": 12, "skin_types": ["oily", "combination"], "concerns": ["pores"], "sensitive_safe": True, "actives": False, "ingredient": "Ice Plant, Baobab Water", "blurb": "The budget champion of Korean sunscreens. Watery gel, zero cast, single-digit-adjacent price."},
    {"id": "anua-airysun", "brand": "Anua", "name": "Heartleaf Airy Sun Cream SPF50+", "category": "spf", "price": 18, "skin_types": ["oily", "combination"], "concerns": ["pores", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Heartleaf, Sebum-Control Powder", "blurb": "Weightless, semi-matte, and actually helps control shine through the day. Oily skin's SPF excuse-remover."},
    {"id": "numbuzin-sunessence", "brand": "Numbuzin", "name": "No.1 Clear Filter Sun Essence SPF50+", "category": "spf", "price": 22, "skin_types": ["all"], "concerns": ["dullness", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Glutathione, Niacinamide", "blurb": "Sunscreen with the 'clear filter' effect: a subtle tone-up glow that never clogs or pills."},
    {"id": "tocobo-sunstick", "brand": "Tocobo", "name": "Cotton Soft Sun Stick SPF50+", "category": "spf", "price": 15, "skin_types": ["all"], "concerns": [], "sensitive_safe": True, "actives": False, "ingredient": "Cotton Extract, Matte Powders", "blurb": "The reapplication problem, solved. Swipe over makeup at lunch; matte cotton finish, no mess."},
    {"id": "dalba-sun", "brand": "d'Alba", "name": "Waterfull Essence Sun Cream SPF50+", "category": "spf", "price": 28, "skin_types": ["dry", "normal"], "concerns": ["dehydration", "aging"], "sensitive_safe": True, "actives": False, "ingredient": "White Truffle, Hyaluronic Acid", "blurb": "The luxury-feeling daily SPF. Essence-like slip and a dewy finish that flatters dry skin."},
    {"id": "klairs-uvessence", "brand": "Klairs", "name": "Soft Airy UV Essence SPF50+ PA++++", "category": "spf", "price": 20, "skin_types": ["oily", "combination", "normal"], "concerns": ["pores"], "sensitive_safe": True, "actives": False, "ingredient": "Niacinamide, Sea Buckthorn Oil", "blurb": "An essence-thin sunscreen with niacinamide and sea buckthorn folded in. Sinks in matte and quiet -- built for combination and oily skin that hates a sunscreen finish."},
    {"id": "purito-centellasun", "brand": "Purito", "name": "Centella Green Level Unscented Sun SPF50+ PA++++", "category": "spf", "price": 19, "skin_types": ["all"], "concerns": ["redness"], "sensitive_safe": True, "actives": False, "ingredient": "Centella Asiatica Extract, Madecassoside", "blurb": "EWG-green, fragrance-free, and dosed with real centella instead of scent. The unscented, sensitive-skin default for daily reapplication."},
    {"id": "axisy-nostresssun", "brand": "AXIS-Y", "name": "Complete No-Stress Physical Sunscreen SPF50+ PA++++", "category": "spf", "price": 20, "skin_types": ["normal", "combination", "oily"], "concerns": ["redness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Zinc Oxide, Niacinamide, Mugwort Extract", "blurb": "A 100% mineral filter softened with niacinamide, squalane, and mugwort. No-stress by name -- pregnancy-safe and built for skin that reacts to everything else."},
    {"id": "etude-sunprise", "brand": "Etude", "name": "Sunprise Mild Airy Finish Sun Milk SPF50+ PA+++", "category": "spf", "price": 12, "skin_types": ["all"], "concerns": ["redness"], "sensitive_safe": True, "actives": False, "ingredient": "Zinc Oxide, Centella Asiatica, Aloe", "blurb": "Etude's mild-format sunscreen, light enough for kids and calm enough for reactive adults. Centella and aloe keep the zinc oxide from feeling chalky."},
    {"id": "innisfree-perfectuv", "brand": "innisfree", "name": "Perfect UV Protection Cream Triple Care SPF50+ PA+++", "category": "spf", "price": 14, "skin_types": ["normal", "combination", "all"], "concerns": ["dullness", "aging"], "sensitive_safe": True, "actives": False, "ingredient": "Niacinamide, Jeju Green Tea Extract", "blurb": "A three-in-one cream pulling double duty as UV shield, dark-spot fader, and fine-line softener via niacinamide and Jeju green tea. The daily-wear default before K-beauty got trendy."},
    {"id": "sbm-truecicasun", "brand": "Some By Mi", "name": "Truecica Mineral 100 Calming Suncream SPF50+ PA++++", "category": "spf", "price": 20, "skin_types": ["oily", "combination", "all"], "concerns": ["acne", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Non-Nano Zinc Oxide, Tea Tree Leaf Water", "blurb": "Zinc oxide and titanium dioxide only, no chemical filters, backed by a heavy dose of tea tree water. Built for acne-prone and reactive skin that flares at anything else."},
    {"id": "neogen-daylightsun", "brand": "Neogen", "name": "Day-Light Protection Sun Screen SPF50 PA+++", "category": "spf", "price": 17, "skin_types": ["all"], "concerns": ["dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Titanium Dioxide, Zinc Oxide, Portulaca Extract", "blurb": "A lightweight daily formula layering mineral and chemical filters with portulaca and berry antioxidants. Sinks in fast enough to skip the sunscreen procrastination."},
    {"id": "drg-poreblursun", "brand": "Dr.G", "name": "Pore Blur Up Sun SPF50+ PA++++", "category": "spf", "price": 20, "skin_types": ["combination", "oily", "normal"], "concerns": ["texture", "pores"], "sensitive_safe": True, "actives": False, "ingredient": "Soft-Focus Powder, Niacinamide, Titanium Dioxide", "blurb": "Exactly what the name promises: a soft-focus powder blurs visible pores and texture on contact, no color-correcting gimmick required. The rare sunscreen that doubles as a makeup primer."},
    {"id": "drjart-premiumbb", "brand": "Dr.Jart+", "name": "Premium Beauty Balm SPF45", "category": "spf", "price": 42, "skin_types": ["dry", "normal", "all"], "concerns": ["texture", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Niacinamide, Adenosine, Mineral SPF (Titanium Dioxide, Zinc Oxide)", "blurb": "Part BB cream, part sunscreen: mineral filters plus niacinamide and adenosine blur uneven texture and dullness on dry skin while protecting it. The multitasker that started Korea's beauty-balm category."},
    # ---------- WEEKLY TREATS (14) ----------
    {"id": "mediheal-teatree", "brand": "Mediheal", "name": "Tea Tree Essential Sheet Mask", "category": "mask", "price": 2, "skin_types": ["oily", "combination", "all"], "concerns": ["acne", "redness"], "sensitive_safe": True, "actives": False, "ingredient": "Tea Tree, Cica", "blurb": "Korea's #1 sheet mask brand. A 20-minute calm-down for breakout weeks."},
    {"id": "imfrom-rice", "brand": "I'm From", "name": "Rice Mask (Wash-off)", "category": "mask", "price": 30, "skin_types": ["dry", "normal", "all"], "concerns": ["dullness", "texture", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Yeoju Rice Bran", "blurb": "A once-a-week glow treatment that combines gentle exfoliation with deep nourishment."},
    {"id": "biodance-collagen", "brand": "Biodance", "name": "Bio-Collagen Real Deep Mask", "category": "mask", "price": 19, "skin_types": ["all"], "concerns": ["aging", "dehydration", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Low-Molecular Collagen, Galactomyces", "blurb": "The viral overnight hydrogel that turns transparent as it sinks in. Wake up to bouncy, glassy skin."},
    {"id": "bj-ricehoney", "brand": "Beauty of Joseon", "name": "Ground Rice and Honey Glow Mask", "category": "mask", "price": 18, "skin_types": ["combination", "oily", "normal"], "concerns": ["pores", "texture", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Rice Powder, Honey, Makgeolli Lees", "blurb": "A weekly wash-off that pulls out gunk with kaolin clay, then buffs and brightens with rice and honey."},
    {"id": "laneige-sleeping", "brand": "Laneige", "name": "Water Sleeping Mask", "category": "mask", "price": 25, "skin_types": ["dry", "normal", "combination"], "concerns": ["dehydration", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Squalane, Sleep-Tox Complex", "blurb": "The overnight classic from Korea's hydration house. Seals your routine in while you sleep."},
    {"id": "medicube-wrap", "brand": "Medicube", "name": "Collagen Night Wrapping Mask", "category": "mask", "price": 21, "skin_types": ["dry", "normal", "all"], "concerns": ["aging", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Collagen Extract, Ceramide NP, Adenosine", "blurb": "A peel-off-style overnight wrap that firms and plumps by morning. K-beauty's answer to the salmon-DNA facial craze."},
    {"id": "innisfree-volcanic", "brand": "innisfree", "name": "Super Volcanic Pore Clay Mask 2X", "category": "mask", "price": 15, "skin_types": ["oily", "combination"], "concerns": ["pores", "acne", "texture"], "sensitive_safe": True, "actives": False, "ingredient": "Jeju Volcanic Clusters", "blurb": "Jeju Island's volcanic clay vacuums out sebum without leaving skin desert-dry. The oily-skin weekly reset."},
    {"id": "mediheal-collagen", "brand": "Mediheal", "name": "Collagen Essential Sheet Mask", "category": "mask", "price": 2, "skin_types": ["dry", "normal", "all"], "concerns": ["aging", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Collagen, Elastin", "blurb": "The firming entry in Korea's best-selling mask lineup. Twenty minutes to a plumper-looking face."},
    {"id": "mediheal-madecassoside", "brand": "Mediheal", "name": "Madecassoside Essential Sheet Mask", "category": "mask", "price": 2, "skin_types": ["all"], "concerns": ["redness", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Madecassoside, Cica", "blurb": "Blemish-repair in sheet form. The one to reach for the morning after your skin freaks out."},
    {"id": "abib-sheetmask", "brand": "Abib", "name": "Mild Acidic pH Sheet Mask Heartleaf Fit", "category": "mask", "price": 3, "skin_types": ["all"], "concerns": ["redness", "dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "Heartleaf, Mild Acidic pH", "blurb": "A whisper-thin gauze sheet at skin-friendly pH. Calm, hydrated, done."},
    {"id": "torriden-sheetmask", "brand": "Torriden", "name": "Dive-In Low Molecular HA Mask Sheet", "category": "mask", "price": 2, "skin_types": ["all"], "concerns": ["dehydration"], "sensitive_safe": True, "actives": False, "ingredient": "5 Sizes of Hyaluronic Acid", "blurb": "The Dive-In serum, soaked into a sheet. Pure hydration with nothing to react to."},
    {"id": "skinfood-rice", "brand": "SKINFOOD", "name": "Rice Mask Wash Off", "category": "mask", "price": 12, "skin_types": ["all"], "concerns": ["dullness", "texture"], "sensitive_safe": True, "actives": False, "ingredient": "Rice Extract, Rice Bran", "blurb": "A milky rice scrub-mask that's been a Korean staple for a decade. Soft-focus skin on a budget."},
    {"id": "bj-redbean", "brand": "Beauty of Joseon", "name": "Red Bean Refreshing Pore Mask", "category": "mask", "price": 17, "skin_types": ["oily", "combination"], "concerns": ["pores", "acne"], "sensitive_safe": True, "actives": False, "ingredient": "Red Bean, Kaolin Clay", "blurb": "A gentle clay wash-off that keeps pores and sebum in check without the tight, chalky aftermath."},
    {"id": "goodal-vitc-mask", "brand": "Goodal", "name": "Green Tangerine Vita C Dark Spot Care Serum Sheet Mask", "category": "mask", "price": 4, "skin_types": ["all"], "concerns": ["dark-spots", "dullness"], "sensitive_safe": True, "actives": False, "ingredient": "Green Tangerine Vitamin C, Niacinamide", "blurb": "A hypoallergenic microfiber sheet steeped in peak-season green tangerine. The weekly reach for stubborn dark spots and uneven tone."},
]


def validate_products(products, concern_ids):
    """Validate curated product rows before they ever reach the DB.

    A malformed row (missing/misspelled field, unknown category, concern id
    that doesn't exist, etc.) doesn't error anywhere in scoring.py — it just
    silently never matches. Fail loudly here instead. Raises ValueError on the
    first violation found, naming the offending product's id/index and the
    exact rule that failed.

    Only applies to curated products (this module's PRODUCTS) — import_external.py
    intentionally inserts "external" rows with empty skin_types/concerns by
    design and must never be run through this.
    """
    seen_ids: set[str] = set()

    for index, product in enumerate(products):
        label = product.get("id") or f"<index {index}>"

        for field in REQUIRED_PRODUCT_FIELDS:
            if field not in product:
                raise ValueError(f"Product {label}: missing required field '{field}'")

        product_id = product["id"]
        if not isinstance(product_id, str) or not product_id.strip():
            raise ValueError(f"Product {label}: 'id' must be a non-empty string")
        if product_id in seen_ids:
            raise ValueError(f"Product {product_id}: duplicate id — ids must be unique")
        seen_ids.add(product_id)

        for field in ("brand", "name", "ingredient"):
            value = product[field]
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"Product {product_id}: '{field}' must be a non-empty string")

        category = product["category"]
        if category not in VALID_CATEGORIES:
            raise ValueError(
                f"Product {product_id}: invalid category '{category}' "
                f"(must be one of {sorted(VALID_CATEGORIES)})"
            )

        skin_types = product["skin_types"]
        if not isinstance(skin_types, list) or not skin_types:
            raise ValueError(f"Product {product_id}: 'skin_types' must be a non-empty list")
        for skin_type in skin_types:
            if skin_type not in VALID_SKIN_TYPES:
                raise ValueError(
                    f"Product {product_id}: invalid skin_type '{skin_type}' "
                    f"(must be one of {sorted(VALID_SKIN_TYPES)})"
                )

        concerns = product["concerns"]
        if not isinstance(concerns, list):
            raise ValueError(f"Product {product_id}: 'concerns' must be a list")
        for concern in concerns:
            if concern not in concern_ids:
                raise ValueError(
                    f"Product {product_id}: invalid concern '{concern}' "
                    f"(must be one of {sorted(concern_ids)})"
                )

        for field in ("sensitive_safe", "actives"):
            value = product[field]
            if not isinstance(value, bool):
                raise ValueError(
                    f"Product {product_id}: '{field}' must be a bool, got {type(value).__name__}"
                )
